export type Quote = {
  id: number
  text: string
  context?: string
  author: string
}

// Dumme Solution kein bock Magie zu machen oder DB zeug
export const quotes: readonly Quote[] = [
  { id: 1, text: 'Das muss ich, glaube ich korrigieren. [...] Das ist irgendwie durch Copy-Paste, man soll ja nie Copy-Paste machen,[..] Warum ist das niemals früher aufgefallen. Ich habe diese Folie schon seit Jahren und warum ist das weder mir noch jemand anderem aufgefallen. Warum ist das jetzt mir aufgefallen.', context: 'nach sieben Jahren FOP', author: 'Karsten Weihe' },
  { id: 2, text: 'Ich glaube das heißt Alsmeier oder so', context: 'KW nachdem Studierende seinen Tafelanschrieb in Graphenalgorithmen korrigieren', author: 'Karsten Weihe' },
  { id: 3, text: 'Und implementieren heißt jedenfalls implementieren', author: 'Karsten Weihe' },
  { id: 4, text: 'Was habe ich da geschrieben?! Wie heißt das Ding? Alz.. alz.. meier? Alzmeier?!', author: 'Karsten Weihe' },
  { id: 5, text: 'Wenn ich keine Smartphones mehr sehe, dann schreite ich zur Tat', author: 'Karsten Weihe' },
  { id: 6, text: 'Wir sind da mit den Juristen leider in einem Boot.', author: 'Karsten Weihe' },
  { id: 7, text: 'Wer Informatik gewählt hat, ist ein Liebhaber der Mathematik. Was, kein Wiederspruch?', author: 'Karsten Weihe' },
  { id: 8, text: 'Ich darf Sie begrüßen zur vierzehnt-letzten Woche der Vorlesungszeit.', author: 'Karsten Weihe' },
  { id: 9, text: 'Ab nächste Woche sehen Sie mich öfters.', context: 'KW bei Erstisbegruessung', author: 'Karsten Weihe' },
  { id: 10, text: 'Im Deutschunterricht haben Sie vielleicht gelernt, man soll nicht das immer auf die selbe Art sagen / schreiben, ABER in jedem Bereich, in dem es um richtig was geht, und in der Informatik geht es regelmäßig um hohe Sachwerte und nicht selten Menschenleben, werden wird immer dieselbe Formelhafte Form genutzt.', author: 'Karsten Weihe' },
  { id: 11, text: 'Frischer Doktor wird mit Wagen durch die Vorlesung gefahren: "Wir haben jetzt ihre Stimmen und Gesichter aufgezeichnet das hier ist eine Vorlesung über Stimm- und Gesichtsverarbeitung und Sie bekommen dann Post von der Personalabteilung!', context: 'KW in FOP', author: 'Karsten Weihe' },
  { id: 12, text: 'Ich bitte um Nachsicht für eventuelle rüde Sprache, die mal irgendwann passiert ist, aber rausgeschnitten werden wird', author: 'Karsten Weihe' },
  { id: 13, text: 'Scheint als hätten meine Studis zu viel Zeit', context: 'KW als ich ihm maymay gerade gezeigt habe^^', author: 'Karsten Weihe' },
  { id: 14, text: 'Zweimal das gleiche Schema, immer das gleiche Schema', context: 'KW will damit nicht zitiert werden', author: 'Karsten Weihe' },
  { id: 15, text: 'Sagt Ihnen das Wort Schallplatte noch etwas? Bitte sagen Sie ja, sonst fühl ich mich so alt. OH? Tut es? Vielen Dank, das hat mir den Tag gerettet.', author: 'Karsten Weihe' },
  { id: 16, text: 'Was wir hier machen ist eine Bewusstseinserweiterung', context: 'über Listen... oder semilegale Substanzen idk', author: 'Karsten Weihe' },
  { id: 17, text: 'Raten sie wie diese Klasse der Programmiersprachen heist. Das sind die funktionalen Programmiersprachen.', author: 'Karsten Weihe' },
  { id: 18, text: 'das geht auch ohne Rekursionsabbruch', author: 'Karsten Weihe' },
  { id: 19, text: 'Alles kann überall reingesteckt werden', context: 'über Datentypen', author: 'Karsten Weihe' },
  { id: 20, text: 'Was ist die Oberklasse von Vögeln? ... Tiere, nicht?', author: 'Karsten Weihe' },
  { id: 21, text: 'Vielleicht müssen Sie ihre Maske aufsetzten, dann hören Sie besser.', author: 'Karsten Weihe' },
  { id: 22, text: 'Wer If-Schleife sagt, gibt ne Runde aus', author: 'Karsten Weihe' },
  { id: 23, text: 'Wenn sich jemand nicht an die Konventionen hält, mögen ihm die Finger and der Tastatur festfrieren', author: 'Karsten Weihe' },
  { id: 24, text: 'In der FOP wollen wir Java entfernen. Ääähm erlernen.', author: 'Karsten Weihe' },
  { id: 25, text: 'Heute! also Morgen', context: 'hat Prokrastination verstanden', author: 'Karsten Weihe' },
  { id: 26, text: 'Sagen sie das, was ich ihnen hier sage, bitte nicht den Hardwareleuten, die werden mich finden', author: 'Karsten Weihe' },
  { id: 27, text: 'Ich finds toll, aber ich muss auch die Klausur nicht schreiben', author: 'Karsten Weihe' },
  { id: 28, text: 'Das können sie vergessen, ich will gar nicht wissen was das ist', author: 'Karsten Weihe' },
  { id: 29, text: 'ich benutz jetzt mal nen anderen PDF-Reader', context: 'der edge benutzt', author: 'Karsten Weihe' },
  { id: 30, text: 'Die Technik hat es auf mich abgesehen', author: 'Karsten Weihe' },
  { id: 31, text: 'Vor ein paar Jahren, als ich noch meinen alten Laptop genutzt habe, ist jedes mal, wenn ich bei einem PDF den Präsentationsmodus aufgemacht habe, impierisch das licht ausgegangen', author: 'Karsten Weihe' },
  { id: 32, text: 'Wir enden mit Grimms Märchen', author: 'Karsten Weihe' },
  { id: 33, text: 'sagen sie das ist ein Cyberangriff', author: 'Karsten Weihe' },
  { id: 34, text: 'Nech', author: 'Karsten Weihe' },
  { id: 35, text: 'Wir sehen uns wieder am Donnerstag um 8 Uhr - Sie wollten Präsenz, sie kriegen Präsenz!', author: 'Karsten Weihe' },
  { id: 36, text: 'In der Informatik haben wir erstmal das Problem, dass wir verschiedene Programmiersprachen haben...', author: 'Karsten Weihe' },
  { id: 37, text: 'Das sehen wir uns an einem einzelnen, leidlich realistischen Beispiel an.', author: 'Karsten Weihe' },
  { id: 38, text: 'Der brexit hat den Wettlauf gegen den BER gewonnen', author: 'Karsten Weihe' },
  { id: 39, text: '... dann wissen sie, wo der Hase begraben ist', context: 'erklärt Fehlersuche', author: 'Karsten Weihe' },
  { id: 40, text: 'Die Relation ist offensichtlich auch antisemitisch.... nein, antisymmetrisch. Man sollte keine Nachrichten vor der Vorlesung schauen *kichert*', author: 'Karsten Weihe' },
  { id: 41, text: 'Früher waren es mehrere tausend Bytes, heute sind es sogar mehrere Kilobyte', context: 'über Daten, die gleichzeitig aus dem Hintergrundspeicher geladen werden können', author: 'Karsten Weihe' },
  { id: 42, text: 'Jargon File... File - wie das englische Wort File', author: 'Karsten Weihe' },
  { id: 43, text: 'Dazu ein Wort ... Bean .... Bean wie Bohne', context: 'über Java Beans', author: 'Karsten Weihe' },
  { id: 44, text: '...heuristische Regel heißt gilt nicht...', author: 'Karsten Weihe' },
  { id: 45, text: 'Da ist die Klammer-Auf und da ... mhhh, ja... da irgendwo ist die Klammer-Zu', context: 'Zusammenfassung Racket in einem Satz', author: 'Karsten Weihe' },
  { id: 46, text: 'Keine Sorge, Mathematik ist jetzt nichts schlechtes', author: 'Karsten Weihe' },
  { id: 47, text: 'Heute werden wir mit Racket, einer funktionalen Sprache, mal etwas aus der FOP rauskommen.', context: 'über Funktionale und objektorientierte Programmierprojekte', author: 'Karsten Weihe' },
  { id: 48, text: 'Entititität', author: 'Karsten Weihe' },
  { id: 49, text: 'Klicken sie hier, klicken sie hier und wie sie sehen, sehen sie nix', author: 'Karsten Weihe' },
  { id: 50, text: 'Es trifft den, der abgeschrieben hat und auch den, der abgeschrieben hat.', author: 'Karsten Weihe' },
  { id: 51, text: '... und Java könnte man mit einem zugedrückten Auge als eine vernünftige Programmiersprache ansehen', author: 'Karsten Weihe' },
  { id: 52, text: 'Ich muss gestehen ich bin auch nicht in die Vorlesungen gegangen... Und Sie sehen was aus mir geworden ist', author: 'Karsten Weihe' },
  { id: 53, text: 'Jeder Baum ist auch ein Wald, aber nicht jeder Wald ist auch ein Baum', context: 'AuD SS2017', author: 'Karsten Weihe' },
  { id: 54, text: 'Wieso muss man wenigstens Informatik studiert haben um Fotos machen zu können?', context: 'nachdem er versucht hat mit seinem eigenen Handy die Tafel abzufotografieren', author: 'Karsten Weihe' },
  { id: 55, text: '2 * 11 - 3? Ist 19, oder? Naja, ist ja auch egal, kann der Computer berechnen...', author: 'Karsten Weihe' },
]
